# Use this image as the platform to build the app
FROM node:21-alpine AS builder

# The WORKDIR instruction sets the working directory for everything that will happen next
WORKDIR /app

# Copy all local files into the image
COPY ./src/frontend .

# Clean install all node modules
RUN npm install

# Build SvelteKit app
RUN npm run build

# This is the command that will be run inside the image when you tell Docker to start the container
CMD ["node","build/index.js"]
