# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_providers {
      aws = {
          source = "hashicorp/aws"
          version = "~>4.0"
      }
  }
}

provider "aws" {
  region = "us-east-1"
  profile = "saml"
  default_tags {
      tags = {
          email = "forrestmillerj@gmail.com"
      }
  }
}
