<script>
    import {emote, top_emotes, channel, chart_data, chart_options, limit, interval, donut_chart_options} from './dashboard/store.ts'
    import { browser } from '$app/environment';
	import { onMount } from 'svelte';
    
    
    
    onMount(async () => {
        if (browser) {
            if ($channel != '') {
                console.log("updating chart");
                const domain = "https://chat-stat-api.fomiller-cluster.dev.aws.fomillercloud.com";
                let endpoint = `api/channel/${$channel}/top/?limit=${$limit}&interval=${$interval}`;
                let response = await fetch(`${domain}/${endpoint}`);
                let data = await response.json();
                
                data["rows"].forEach((e) => $top_emotes.push({"name": e[0], "value": e[1]}))
                console.log($top_emotes)
                $donut_chart_options.labels = Array.from($top_emotes, (x) => x.name)
                $donut_chart_options.series = Array.from($top_emotes, (x) => Number(x.value))
            }
            if (document.getElementById("donut-chart") && typeof ApexCharts !== 'undefined') {
                const chart = new ApexCharts(document.getElementById("donut-chart"), $donut_chart_options);
                chart.render();
            }
        }
	});
</script>

<div class="min-w-full w-full bg-white rounded-lg shadow dark:bg-gray-800 my-4 p-4 md:p-6">
  
  <div class="flex justify-between mb-3">
      <div class="flex justify-center items-center">
          <h5 class="text-xl font-bold leading-none text-gray-900 dark:text-white pe-1">{$channel}'s top {$limit} emotes over {$interval}</h5>
          <div data-popover id="chart-info" role="tooltip" class="absolute z-10 invisible inline-block text-sm text-gray-500 transition-opacity duration-300 bg-white border border-gray-200 rounded-lg shadow-sm opacity-0 w-72 dark:bg-gray-800 dark:border-gray-600 dark:text-gray-400">
              <div class="p-3 space-y-2">
                  <h3 class="font-semibold text-gray-900 dark:text-white">Activity growth - Incremental</h3>
                  <p>Report helps navigate cumulative growth of community activities. Ideally, the chart should have a growing trend, as stagnating chart signifies a significant decrease of community activity.</p>
                  <h3 class="font-semibold text-gray-900 dark:text-white">Calculation</h3>
                  <p>For each date bucket, the all-time volume of activities is calculated. This means that activities in period n contain all activities up to period n, plus the activities generated by your community in period.</p>
                  <a href="#" class="flex items-center font-medium text-blue-600 dark:text-blue-500 dark:hover:text-blue-600 hover:text-blue-700 hover:underline">Read more <svg class="w-2 h-2 ms-1.5 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
            </svg></a>
              </div>
              <div data-popper-arrow></div>
          </div>
        </div>
  </div>

  <!-- Donut Chart -->
  <div class="py-6" id="donut-chart"></div>

  <div class="grid grid-cols-1 items-center border-gray-200 border-t dark:border-gray-700 justify-between">
    <div class="flex justify-between items-center pt-5">
      <!-- Button -->
      <!-- <button -->
      <!--   id="dropdownDefaultButton" -->
      <!--   data-dropdown-toggle="lastDaysdropdown" -->
      <!--   data-dropdown-placement="bottom" -->
      <!--   class="text-sm font-medium text-gray-500 dark:text-gray-400 hover:text-gray-900 text-center inline-flex items-center dark:hover:text-white" -->
      <!--   type="button"> -->
      <!--   Last 7 days -->
      <!--   <svg class="w-2.5 m-2.5 ms-1.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6"> -->
      <!--     <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4"/> -->
      <!--   </svg> -->
      <!-- </button> -->
      <!-- <div id="IntervalDropdown" class="z-10 hidden bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700"> -->
      <!--     <ul class="py-2 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="dropdownDefaultButton"> -->
      <!--       <li> -->
      <!--         <a href="#" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Yesterday</a> -->
      <!--       </li> -->
      <!--       <li> -->
      <!--         <a href="#" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Today</a> -->
      <!--       </li> -->
      <!--       <li> -->
      <!--         <a href="#" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Last 7 days</a> -->
      <!--       </li> -->
      <!--       <li> -->
      <!--         <a href="#" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Last 30 days</a> -->
      <!--       </li> -->
      <!--       <li> -->
      <!--         <a href="#" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Last 90 days</a> -->
      <!--       </li> -->
      <!--     </ul> -->
      <!-- </div> -->
    </div>
  </div>
</div>
